### ISSUE TITLE
Crashes in anonymous views; should guess path from window folders

### ISSUE THREAD

**Issue by mitranim** [roadhump/SublimeLinter-contrib-eslint_d#15]
(EDIT: apparently fixed 2 years ago, needs to be published. See below.)

At the time of writing (version `1.1.1`), the plugin crashes when trying to lint an anonymous buffer:

```
SublimeLinter: #3803 eslint_d <untitled 817> ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/mitranim/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/mitranim/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 797, in lint
  File "lint.linter in /Users/mitranim/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 1139, in run
  File "linter in /Users/mitranim/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-eslint_d.sublime-package", line 78, in communicate
  File "./python3.3/posixpath.py", line 458, in relpath
ValueError: no path specified
```

This has always been happening. As a result, the plugin doesn't work on anonymous buffers. It got annoying with the release of Sublime Linter 4, which pumps these exceptions into the foreview instead of hiding them in the Sublime console.

I suggest guessing the anonymous view path from the current window, similarly to how RustFmt does it ([code](https://github.com/Mitranim/sublime-rust-fmt/blob/69a1dc0c8451d4ff2ac736345bd1705cc948c1f6/RustFmt.py#L75)). In addition, avoid crashing when no path is available.

**Comment by mitranim** [comment]
Cloned the repo to try and fix the issue, and it just works. Apparently, 924dac299a37206310837c16ea7ede8174d8d489 is responsible for the fix, but it hasn't been released to Package Control. Please release it. Btw it looks like this commit left some junk code related to the feature it removed; that should probably be cleaned up.

On a side note, the plugin still crashes in anonymous buffers _outside_ of a project when you don't have `eslint_d` installed globally (I don't).

**Comment by kaste** [comment]
You should maybe just use `eslint` here

https://github.com/SublimeLinter/SublimeLinter/issues/1187#issuecomment-372252683

**Comment by mitranim** [comment]
@kaste Thanks for the response, but I don't understand what you mean. The crash happens in the plugin's Python code, not in the JS executable.

**Comment by kaste** [comment]
Did you read the comment I linked to?

**Comment by mitranim** [comment]
Yes, and I don't understand what you mean. Would be nice if you can rephrase it.

**Comment by kaste** [comment]
Use the SublimeLinter eslint plugin and trick it into using eslint_d executable instead of the default eslint.

**Comment by mitranim** [comment]
Neat idea. I always install `eslint_d` locally; not sure how to tell the plugin where to find it. Any clues?

**Comment by mitranim** [comment]
Nevermind, found the [executable setting docs](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/linter_settings.rst#executable).

**Comment by kaste** [comment]
Hm. It's usually ${folder}/node_modules/bin/eslint_d

**Comment by mitranim** [comment]
For me it's actually `"${folder}/node_modules/.bin/eslint_d"`. Not sure if `bin` without the dot would work for anyone...

**Comment by kaste** [comment]
C'mon it's a typo, of course with the dot.

**Comment by mitranim** [comment]
Seems to be working, and it properly uses the background Node process instead of spawning a new one. Thanks for the advice; I'll probably stick with `SublimeLinter-eslint` now since it's better maintained.

It would be really nice if the `SublimeLinter-eslint` docs recommended using `eslint_d` instead of `eslint`, since it's so much faster and provides such a better experience. The fact it exists, and that it's usable with the "stock" plugin instead of the apparently buggier `SublimeLinter-contrib-eslint_d`, is valuable knowledge that shouldn't be kept arcane.

**Comment by kaste** [comment]
PRs for the README are always welcome 😄 

However, the main problem here is that the daemon should be killed at some time (which this plugin here never did as well).

**Comment by mitranim** [comment]
Yeah but I consider this a minor issue. The daemon doesn't seem to use any CPU when idle, and the recent versions don't seem to leak memory as rapidly. On balance, it's nowhere near as decadent as spawning a new Node process every time. 🙂
