### ISSUE TITLE
 it dosnot work after updated SublimeLinter

### ISSUE THREAD

**Issue by laozhujia** [roadhump/SublimeLinter-contrib-eslint_d#19]
SublimeLinter: ERROR:
=====================

eslint_d: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.

SublimeLinter: ERROR:
=====================

eslint_d: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.

SublimeLinter: ERROR:
=====================

eslint_d disabled. 'cls.defaults' is mandatory and MUST be a dict.

**Comment by piyuple** [comment]
Hi, I'm facing this same error. Were you able to get a fix?
