### ISSUE TITLE
Doesn't use .eslintignore

### ISSUE THREAD

**Issue by jonvuri** [roadhump/SublimeLinter-contrib-eslint_d#8]
When I use this plugin in Sublime Text 3 it doesn't respect any .eslintignore files. Switching to the normal eslint plugin with the same project makes it work correctly.

**Comment by roadhump** [comment]
I remove skipping of .eslintignore check (suppose it was some early code), can you check new version?

**Comment by jonvuri** [comment]
Yep! It works great now. Thanks!
