### ISSUE TITLE
netcat mode?

### ISSUE THREAD

**Issue by benmosher** [roadhump/SublimeLinter-contrib-eslint_d#9]
Have you considered talking to the server directly? 

https://www.npmjs.com/package/eslint_d#moar-speed

Just curious. I'm tempted to fork and attempt.

**Comment by roadhump** [comment]
No, feel free to try

**Comment by benmosher** [comment]
I tried. I'm not familiar with SublimeLinter, but it doesn't seem to like the idea running a shell command that doesn't start with an executable. (which makes sense.)

I give up, existing mode of execution is plenty fast. :smile:
